CREATE TABLE IF NOT EXISTS Entry (
    id INTEGER PRIMARY KEY,
    mediaId INTEGER,
    status INTEGER,
    completedDay INTEGER,
    completedMonth INTEGER,
    completedYear INTEGER,
    notes TEXT,
    private BOOLEAN,
    progress INTEGER,
    repeat INTEGER,
    score INTEGER,
    isFavourite BOOLEAN,
    startedDay INTEGER,
    startedMonth INTEGER,
    startedYear INTEGER,
    anilistModified INTEGER,
    modified INTEGER,
    FOREIGN KEY (mediaId) REFERENCES Anime(id),
    FOREIGN KEY (status) REFERENCES EntryStatus(id)
);
